name: Deploy no kubernetes 
on: 
    workflow_call:
        inputs:
            environment-name:
                type: string
                required: true
            environment-url:
                type: string
                required: true

jobs:
    deploy:
        name: Deploy no kubernetes
        runs-on: ubuntu-latest
        environment: 
            name: ${{inputs.environment-name}}
            url: ${{inputs.environment-url}}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup kubectl
              uses: azure/k8s-set-context@v4
              with:
                method: kubeconfig
                kubeconfig: ${{ secrets.K8S_CONFIG }}

            - name: Update deployment
              run: |
                sed -i "s/host: homologacao.wsnobrega.life/host: ${{vars.BASE_URL}}/g" k8s/deployment.yaml
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1                     

            - name: Deploy kubernetes
              uses: Azure/k8s-deploy@v5
              with:
                 namespace: ${{ secrets.K8S_NAMESPACE }}
                 manifests: |
                    k8s/deployment.yaml
                 images: |
                    ${{ vars.ID_ACCOUNT }}.dkr.ecr.${{ vars.AWS_REGION}}.amazonaws.com/review-filmes:${{ github.run_number }}           