name: Deploy no kubernetes 
on: 
    workflow_call:

jobs:
    deploy:
        name: Deploy no kubernetes
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup kubectl
              uses: azure/k8s-set-context@v4
              with:
                method: kubeconfig
                kubeconfig: ${{ secrets.KUBE_CONFIG }}

            - name: Deploy kubernetes
              uses: Azure/k8s-deploy@v5
              with:
                 manifests: |
                    k8s/deployment.yaml
                 images: |
                    ${{ vars.ID_ACCOUNT }}.dkr.ecr.${{ vars.AWS_REGION}}.amazonaws.com/review-filmes:${{ github.run_number }}           