name: Pipeline CI/CD
run-name: Pipeline CI/CD executada por ${{ github.actor }} em ${{ github.run_number }}
permissions:
  id-token: write
  contents: read
  security-events: write

on:
  workflow_dispatch:
  push:
    branches:
      - main 

jobs:
  build:
    name: build 
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v4 
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.300
      - name: executando comando build
        working-directory: ./src
        run: dotnet build Review-Filmes.sln

  testes:
    needs: [build]
    uses: wallafidevops/desafio-actions/.github/workflows/testes.yml@main
    secrets: inherit
  ## secret por herança

  release:
    name: Criação de release
    runs-on: ubuntu-latest
    needs: [testes]
    steps: 
      - name: Obyendo código fonte
        uses: actions/checkout@v4
      - name: Analise Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./src/Review-Filmes.Web/Dockerfile
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1          
             
      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ID_ACCOUNT }}.dkr.ecr.${{ vars.AWS_REGION}}.amazonaws.com
      - name: Build e Push 
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/Review-Filmes.Web/Dockerfile
          push: true
          tags: |
            ${{ vars.ID_ACCOUNT }}.dkr.ecr.${{ vars.AWS_REGION}}.amazonaws.com/review-filmes:latest
            ${{ vars.ID_ACCOUNT }}.dkr.ecr.${{ vars.AWS_REGION}}.amazonaws.com/review-filmes:${{ github.run_number }}
      - name: Executar Trivy
        uses: aquasecurity/trivy-action@0.23.0
        with:
          scan-type: image
          image-ref: ${{ vars.ID_ACCOUNT }}.dkr.ecr.${{ vars.AWS_REGION}}.amazonaws.com/review-filmes:${{ github.run_number }} 
          format: sarif
          output: trivy-docker-result.sarif
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'

      - name: upload do arquivo triy para github 
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: docker-result
          sarif_file: trivy-docker-result.sarif


  deploy-homolog:
    needs: [release]
    uses: wallafidevops/desafio-actions/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      environment-name: homologacao
      environment-url: http://homologacao.wsnobrega.life

  deploy-producao:
    needs: [release]
    uses: wallafidevops/desafio-actions/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      environment-name: producao
      environment-url: http://producao.wsnobrega.life    

      ##20 min