name: Execução de testes
on:
    workflow_call:

jobs:
    unit-testes:
        name: Testes unitários
        runs-on: ubuntu-latest
        steps:           
          - name: Checkout
            uses: actions/checkout@v4 
          - name: Setup dotnet
            uses: actions/setup-dotnet@v4
            with:
              dotnet-version: 8.0.300 
          - name: Executando testes unitários
            working-directory: ./src
            run: dotnet test ./Review-Filmes.Test.Unit/Review-Filmes.Test.Unit.csproj